name: React Native Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'
        
    - name: Create new React Native project
      run: |
        npx react-native init MyApp
        cd MyApp
        echo "Created React Native project"
        
    - name: Install dependencies
      run: |
        cd MyApp
        npm install
        
    - name: Build Android Release APK
      run: |
        cd MyApp
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease
        
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: MyApp/android/app/build/outputs/apk/release/app-release.apk
