name: CC React Native Android Build

on:
  push:
     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    fail-fast: false
    strategy:
      matrix:
        node: [18, 20, 21, 22, 23]
        jdk: [11, 17]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js LTS
      uses: actions/setup-node@v3
      with:
        # node-version: 'lts/*'
        node-version: ${{ matrix.node }}
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
        
    - name: Create new React Native project
      run: |
        git clone https://github.com/cometchat/cometchat-uikit-react-native.git
        cd cometchat-uikit-react-native/examples/SampleApp
        ls
        
    - name: Install dependencies
      run: |
        cd cometchat-uikit-react-native/examples/SampleApp
        npm install
        
    - name: Build Android Release APK
      run: |
        cd cometchat-uikit-react-native/examples/SampleApp
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease
        
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: cometchat-uikit-react-native/examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk
